spring.config.import: "configserver:http://localhost:8081"

spring:
  application:
    name: registry-service
  cloud:
    config:
      enable: true
      uri: http://localhost:8081
      username: root
      password: s3cr3t